server:
  port: 8083

spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessrecommendations
      database: fitnessrecommendations
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


rabbitmq:
  exchange:
    name: activity.exchange
  queue:
    name: activity.gueue
  routing:
    key: activity.tracking